{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Bank API Project",
    "description" : "This is a banking API which handles users, transactions and accounts",
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/project-group/bank-api-2021/1.0.0",
    "description" : "Bank API Project"
  }, {
    "url" : "https://petstore.swagger.io/v2"
  } ],
  "paths" : {
    "/accounts" : {
      "get" : {
        "tags" : [ "account" ],
        "summary" : "get accounts",
        "description" : "getting a list of accounts",
        "operationId" : "getAccounts",
        "responses" : {
          "200" : {
            "description" : "A JSON array of accounts",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Account"
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    },
    "/accounts/" : {
      "post" : {
        "tags" : [ "account" ],
        "summary" : "create an account",
        "description" : "creating an account",
        "operationId" : "createAccount",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "array",
                "items" : {
                  "$ref" : "#/components/schemas/Account"
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Account created successfully"
          },
          "400" : {
            "description" : "Invalid request, account not created"
          }
        }
      }
    },
    "/accounts/{iban}" : {
      "get" : {
        "tags" : [ "account" ],
        "summary" : "get an account using IBAN",
        "description" : "get a specific account using an IBAN",
        "operationId" : "getAccount",
        "parameters" : [ {
          "name" : "iban",
          "in" : "path",
          "description" : "The the iban of the account",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "A json account object",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Account"
                  }
                }
              }
            }
          }
        }
      },
      "delete" : {
        "tags" : [ "account" ],
        "summary" : "Close an account",
        "description" : "Closing an account using an iban",
        "operationId" : "deleteAccount",
        "parameters" : [ {
          "name" : "iban",
          "in" : "path",
          "description" : "The iban account to delete",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Account has been delete successfully"
          }
        }
      }
    },
    "/users" : {
      "get" : {
        "tags" : [ "user" ],
        "summary" : "get users",
        "description" : "getting a list of users",
        "operationId" : "getUsers",
        "responses" : {
          "200" : {
            "description" : "A JSON array of users",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/User"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/" : {
      "post" : {
        "tags" : [ "user" ],
        "summary" : "creating a user",
        "description" : "creating a user",
        "operationId" : "createUser",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/User"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Created a user"
          },
          "400" : {
            "description" : "Invalid request, user not created"
          }
        }
      }
    },
    "/users/{userid}" : {
      "get" : {
        "tags" : [ "user" ],
        "summary" : "get a user using user ID",
        "description" : "get a specific user using an ID",
        "operationId" : "getUser",
        "parameters" : [ {
          "name" : "userid",
          "in" : "path",
          "description" : "The userid of the user",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "A json account object",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/User"
                  }
                }
              }
            }
          }
        }
      },
      "put" : {
        "tags" : [ "user" ],
        "summary" : "update a user",
        "description" : "updating a user using a userid",
        "operationId" : "updateUser",
        "parameters" : [ {
          "name" : "userid",
          "in" : "path",
          "description" : "The userid for the user to update",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/User"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "user has been updated successfully"
          }
        }
      },
      "delete" : {
        "tags" : [ "user" ],
        "summary" : "delete a user",
        "description" : "deleting a user using the userid",
        "operationId" : "deleteUser",
        "parameters" : [ {
          "name" : "userid",
          "in" : "path",
          "description" : "The userid for the user to delete",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "user has been deleted successfully"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Account" : {
        "required" : [ "accountType", "balance", "iban", "user" ],
        "type" : "object",
        "properties" : {
          "iban" : {
            "type" : "string",
            "format" : "uuid"
          },
          "user" : {
            "$ref" : "#/components/schemas/User"
          },
          "balance" : {
            "type" : "integer"
          },
          "accountType" : {
            "$ref" : "#/components/schemas/AccountType"
          }
        }
      },
      "User" : {
        "required" : [ "emailAddress", "firstName", "id", "lastName", "password", "phoneNumber", "role" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "firstName" : {
            "type" : "string"
          },
          "lastName" : {
            "type" : "string"
          },
          "phoneNumber" : {
            "type" : "integer"
          },
          "emailAddress" : {
            "type" : "string",
            "format" : "email"
          },
          "password" : {
            "type" : "string",
            "format" : "password"
          },
          "role" : {
            "$ref" : "#/components/schemas/Role"
          }
        }
      },
      "Transaction" : {
        "required" : [ "accountFrom", "accountTo", "amount", "id", "timestamp", "userPerforming" ],
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "accountFrom" : {
            "$ref" : "#/components/schemas/Account"
          },
          "accountTo" : {
            "$ref" : "#/components/schemas/Account"
          },
          "amount" : {
            "type" : "number"
          },
          "userPerforming" : {
            "$ref" : "#/components/schemas/User"
          },
          "timestamp" : {
            "type" : "string",
            "format" : "date-time"
          }
        }
      },
      "Role" : {
        "type" : "string",
        "enum" : [ "customer", "employee" ]
      },
      "AccountType" : {
        "type" : "string",
        "enum" : [ "current", "savings" ]
      }
    }
  }
}